### ISSUE TITLE
Compare to ResourceTask of Oomph

### ISSUE THREAD

**Issue by maybeec** [maybeec/oomph-task-fscopy#3]
When starting with Oomph evaluation I also tried the ResourceTask for copying and moving files/folders.
As I got to know from one of the authors of Oomph, that this should be already working with the ResourceTask, we should evaluate this once again. It might be, that we can simply go back to ResourceTask or just state a Oomph PR for improvement to match our needs.

**Comment by themetalone** [comment]
I evaluated this a few days ago. As far as I see it the CopyResourceTask only works for single files. Copying a JVM could then result in a rather long setup file.

**Comment by maybeec** [comment]
funny :D ok. So maybe checked whether it is even better to improve that task to also be able to copy folders in future. But of low priority.

**Comment by maybeec** [comment]
What was the result here?

**Comment by themetalone** [comment]
Comparision done. the ResourceCopyTask doesn't seem to be able to handle folders. For the moment FSCopy cannot be replaced by it. On the other hand the download-task may be replaceable (I'm researching that)
